import express from 'express'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import User from '../models/User.js'; import {auth} from '../middleware/auth.js';
const router=express.Router();
const token=u=>jwt.sign({id:u._id},process.env.JWT_SECRET,{expiresIn:'7d'});
router.post('/signup',async(req,res)=>{try{const {name,email,password,role='staff'}=req.body;if(!name||!email||!password) return res.status(400).json({message:'Name, email and password are required'});if(await User.findOne({email})) return res.status(409).json({message:'Email already registered'});const u=await User.create({name,email,password:await bcrypt.hash(password,10),role});res.status(201).json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}});}catch(e){res.status(500).json({message:e.message});}});
router.post('/login',async(req,res)=>{try{const {email,password}=req.body;const u=await User.findOne({email});if(!u||!(await bcrypt.compare(password,u.password))) return res.status(401).json({message:'Invalid email or password'});res.json({token:token(u),user:{id:u._id,name:u.name,email:u.email,role:u.role}});}catch(e){res.status(500).json({message:e.message});}});
router.get('/me',auth,(req,res)=>res.json({user:req.user}));
router.post('/forgot',async(req,res)=>{const u=await User.findOne({email:req.body.email});if(!u)return res.json({message:'If the account exists, an OTP has been generated.'});u.otp=String(Math.floor(100000+Math.random()*900000));u.otpExpires=new Date(Date.now()+10*60*1000);await u.save();console.log(`[StockSense OTP] ${u.email}: ${u.otp}`);res.json({message:'OTP generated. In development, check the backend console.',devOtp:process.env.NODE_ENV==='production'?undefined:u.otp});});
router.post('/reset',async(req,res)=>{const {email,otp,newPassword}=req.body;const u=await User.findOne({email});if(!u||u.otp!==otp||!u.otpExpires||u.otpExpires<Date.now())return res.status(400).json({message:'Invalid or expired OTP'});u.password=await bcrypt.hash(newPassword,10);u.otp=undefined;u.otpExpires=undefined;await u.save();res.json({message:'Password reset successful'});});
export default router;
