import express from 'express'; import Operation from '../models/Operation.js'; import Product from '../models/Product.js'; import Stock from '../models/Stock.js'; import Ledger from '../models/Ledger.js'; import {auth} from '../middleware/auth.js';
const router=express.Router();router.use(auth);
router.get('/',async(req,res)=>{const q={};if(req.query.type)q.type=req.query.type;if(req.query.status)q.status=req.query.status;res.json(await Operation.find(q).populate('items.product','name sku uom').populate('items.warehouse','name').populate('items.toWarehouse','name').sort({createdAt:-1}));});
router.post('/',async(req,res)=>{try{const op=await Operation.create({...req.body,createdBy:req.user._id,reference:req.body.reference||`${req.body.type.toUpperCase()}-${Date.now()}`});res.status(201).json(await op.populate('items.product','name sku uom'));}catch(e){res.status(400).json({message:e.message});}});
router.post('/:id/validate',async(req,res)=>{try{const op=await Operation.findById(req.params.id);if(!op)return res.status(404).json({message:'Operation not found'});if(op.status==='Done')return res.status(400).json({message:'Operation already validated'});if(op.status==='Canceled')return res.status(400).json({message:'Canceled operation cannot be validated'});
  for(const item of op.items){
    if(op.type==='receipt'){const s=await Stock.findOneAndUpdate({product:item.product,warehouse:item.warehouse},{$inc:{quantity:item.quantity}},{new:true,upsert:true,setDefaultsOnInsert:true});await Ledger.create({product:item.product,warehouse:item.warehouse,operation:op._id,type:'receipt',quantityChange:item.quantity,balanceAfter:s.quantity,note:op.reference,createdBy:req.user._id});}
    if(op.type==='delivery'){const s=await Stock.findOne({product:item.product,warehouse:item.warehouse});if(!s||s.quantity<item.quantity) return res.status(400).json({message:`Insufficient stock for ${item.product}`});s.quantity-=item.quantity;await s.save();await Ledger.create({product:item.product,warehouse:item.warehouse,operation:op._id,type:'delivery',quantityChange:-item.quantity,balanceAfter:s.quantity,note:op.reference,createdBy:req.user._id});}
    if(op.type==='transfer'){const from=await Stock.findOne({product:item.product,warehouse:item.warehouse});if(!from||from.quantity<item.quantity)return res.status(400).json({message:'Insufficient stock for transfer'});from.quantity-=item.quantity;await from.save();const to=await Stock.findOneAndUpdate({product:item.product,warehouse:item.toWarehouse},{$inc:{quantity:item.quantity}},{new:true,upsert:true,setDefaultsOnInsert:true});await Ledger.create({product:item.product,warehouse:item.warehouse,operation:op._id,type:'transfer-out',quantityChange:-item.quantity,balanceAfter:from.quantity,note:op.reference,createdBy:req.user._id});await Ledger.create({product:item.product,warehouse:item.toWarehouse,operation:op._id,type:'transfer-in',quantityChange:item.quantity,balanceAfter:to.quantity,note:op.reference,createdBy:req.user._id});}
    if(op.type==='adjustment'){const s=await Stock.findOne({product:item.product,warehouse:item.warehouse});const old=s?.quantity||0;const target=item.quantity;const delta=target-old;const ns=await Stock.findOneAndUpdate({product:item.product,warehouse:item.warehouse},{$set:{quantity:target}},{new:true,upsert:true,setDefaultsOnInsert:true});await Ledger.create({product:item.product,warehouse:item.warehouse,operation:op._id,type:'adjustment',quantityChange:delta,balanceAfter:ns.quantity,note:op.reference,createdBy:req.user._id});}
  }
  op.status='Done';op.validatedAt=new Date();await op.save();res.json(op);
}catch(e){res.status(400).json({message:e.message});}});
router.post('/:id/cancel',async(req,res)=>{const op=await Operation.findByIdAndUpdate(req.params.id,{status:'Canceled'},{new:true});res.json(op);});
router.get('/ledger/all',async(req,res)=>{res.json(await Ledger.find().populate('product','name sku').populate('warehouse','name').sort({createdAt:-1}).limit(300));});
export default router;
